import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <string> file_path;
    callback choose-file();
    callback encrypt();
    callback decrypt();
    
    height: 200px;
    width: 200px;

    VerticalBox {
        Text {
            text: file_path;
        }

        VerticalBox {
            Button {
                width: 100px;
                accessible-role: AccessibleRole.button;
                height: 40px;
                text: "Choose File";
                clicked => {
                    root.choose-file();
                }
            }
            Button {
                width: 100px;
                height: 40px;
                text: "Encrypt";
                clicked => {
                    root.encrypt();
                }
            }
            Button {
                width: 100px;
                height: 40px;
                text: "Decrypt";
                clicked => {
                    root.decrypt();
                }
            }
        }
    }
}
