import { Button, VerticalBox, LineEdit, HorizontalBox, ListView } from "std-widgets.slint";
import { PasswordInput } from "app-widgets.slint";

export component AppWindow inherits Window {
    in-out property <string> current_file_path;
    in-out property <[string]> reccent_file_paths;
    callback choose-file();
    callback open-file();
    callback lock-file();
    callback unlock-file();

    width: 400px;

    HorizontalBox {
        VerticalBox {
            width: 70%;

            current_file := Rectangle {
                path := Rectangle {
                    x: 0px;
                    width: parent.width - choose-button.width - 10px;
                    height: 30px;
                    border-color: whitesmoke;
                    border-width: 1px;
                    clip: true;

                    Text {
                        width: 100%;
                        text: current_file_path;
                    }
                }

                choose-button := Button {
                    x: parent.width - self.width;
                    width: path.height + 20px;
                    height: path.height;
                    icon: @image-url("../assets/open_folder.png");

                    clicked => {
                        root.choose-file();
                    }
                }
            }

            VerticalLayout {
                spacing: 5px;

                Text {
                    vertical-alignment: bottom;
                    height: 20px;
                    text: "Recent file";
                }
                
                recent_file := Rectangle {
                    width: 100%;
                    border-color: whitesmoke;
                    border-width: 1px;
    
                    ListView {
                        for p in reccent_file_paths : Button {
                            text: p;
                            
                            clicked => {
                                root.current_file_path = p;
                            }
                        }
                    }
                }
            }
        }

        buttons := VerticalBox {
            width: 100px;

            Button {
                width: 100%;
                height: 40px;
                text: "Open";
                clicked => {
                    root.open-file();
                }
            }

            Button {
                width: 100%;
                height: 40px;
                text: "Lock";
                clicked => {
                    root.lock-file();
                }
            }

            Button {
                width: 100%;
                height: 40px;
                text: "Unlock";
                clicked => {
                    root.unlock-file();
                }
            }
        }
    }
    
}


export component AuthWindow inherits Window {
    height: 40px;
    width: 300px;

    callback authenticate(string);
    
    PasswordInput {
        width: 80%;
        height: 80%;
        background: lightblue;
        placeholder-text: "Enter locker password";
        placeholder-text-color: blue;
        input-text-color: white;
        border-color: blue;
        border-width: 1px;

        accepted(text) => {
            authenticate(text);
        }
    }

}
